### ISSUE TITLE
Error finding gradient of poislogpdf

### ISSUE THREAD

**Issue by dtjohnson** [JuliaStats/StatsFuns.jl#60] opened 2018-10-21 12:09 UTC
I'm getting an error when trying to find the gradient of the `poislogpdf` for a MAP analysis.

```julia
using StatsFuns
using ForwardDiff
ForwardDiff.gradient(x -> poislogpdf(x[1], 2), [0.75])
```

> MethodError: no method matching Float64(::ForwardDiff.Dual{ForwardDiff.Tag{getfield(Main, Symbol("##31#32")),Float64},Float64,1})
> Closest candidates are:
>   Float64(::Real, !Matched::RoundingMode) where T<:AbstractFloat at rounding.jl:185
>   Float64(::T<:Number) where T<:Number at boot.jl:725
>   Float64(!Matched::Int8) at float.jl:60
>   ...
> 
> Stacktrace:
>  [1] convert(::Type{Float64}, ::ForwardDiff.Dual{ForwardDiff.Tag{getfield(Main, Symbol("##31#32")),Float64},Float64,1}) at ./number.jl:7
>  [2] cconvert(::Type, ::ForwardDiff.Dual{ForwardDiff.Tag{getfield(Main, Symbol("##31#32")),Float64},Float64,1}) at ./essentials.jl:344
>  [3] poislogpdf(::ForwardDiff.Dual{ForwardDiff.Tag{getfield(Main, Symbol("##31#32")),Float64},Float64,1}, ::Int64) at /Users/djohnson/.julia/packages/StatsFuns/0W2sM/src/rmath.jl:58
>  [4] (::getfield(Main, Symbol("##31#32")))(::Array{ForwardDiff.Dual{ForwardDiff.Tag{getfield(Main, Symbol("##31#32")),Float64},Float64,1},1}) at ./In[40]:2
>  [5] vector_mode_dual_eval(::getfield(Main, Symbol("##31#32")), ::Array{Float64,1}, ::ForwardDiff.GradientConfig{ForwardDiff.Tag{getfield(Main, Symbol("##31#32")),Float64},Float64,1,Array{ForwardDiff.Dual{ForwardDiff.Tag{getfield(Main, Symbol("##31#32")),Float64},Float64,1},1}}) at /Users/djohnson/.julia/packages/ForwardDiff/hnKaN/src/apiutils.jl:35
>  [6] vector_mode_gradient(::getfield(Main, Symbol("##31#32")), ::Array{Float64,1}, ::ForwardDiff.GradientConfig{ForwardDiff.Tag{getfield(Main, Symbol("##31#32")),Float64},Float64,1,Array{ForwardDiff.Dual{ForwardDiff.Tag{getfield(Main, Symbol("##31#32")),Float64},Float64,1},1}}) at /Users/djohnson/.julia/packages/ForwardDiff/hnKaN/src/gradient.jl:96
>  [7] gradient(::Function, ::Array{Float64,1}, ::ForwardDiff.GradientConfig{ForwardDiff.Tag{getfield(Main, Symbol("##31#32")),Float64},Float64,1,Array{ForwardDiff.Dual{ForwardDiff.Tag{getfield(Main, Symbol("##31#32")),Float64},Float64,1},1}}, ::Val{true}) at /Users/djohnson/.julia/packages/ForwardDiff/hnKaN/src/gradient.jl:17
>  [8] gradient(::Function, ::Array{Float64,1}, ::ForwardDiff.GradientConfig{ForwardDiff.Tag{getfield(Main, Symbol("##31#32")),Float64},Float64,1,Array{ForwardDiff.Dual{ForwardDiff.Tag{getfield(Main, Symbol("##31#32")),Float64},Float64,1},1}}) at /Users/djohnson/.julia/packages/ForwardDiff/hnKaN/src/gradient.jl:15 (repeats 2 times)
>  [9] top-level scope at In[40]:2

Looks like  `poislogpdf` is fine accepting duals but something fails farther in.

**Comment by dtjohnson** [comment] 2018-10-21 12:30
I should add that the gradient works for `normlogpdf`:

```julia
ForwardDiff.gradient(x -> normlogpdf(x[1], x[2], 2), [0.75, 1.0])
```

> 2-element Array{Float64,1}:
>  1.25  
>  0.5625

However, I get the same failure for `gammalogpdf`:
```julia
ForwardDiff.gradient(x -> gammalogpdf(x[1], x[2], 2), [0.75, 1.0])
```

> MethodError: no method matching Float64(::ForwardDiff.Dual{ForwardDiff.Tag{getfield(Main, Symbol("##77#78")),Float64},Float64,2})
> Closest candidates are:
>   Float64(::Real, !Matched::RoundingMode) where T<:AbstractFloat at rounding.jl:185
>   Float64(::T<:Number) where T<:Number at boot.jl:725
>   Float64(!Matched::Int8) at float.jl:60
>   ...
> 
> Stacktrace:
>  [1] convert(::Type{Float64}, ::ForwardDiff.Dual{ForwardDiff.Tag{getfield(Main, Symbol("##77#78")),Float64},Float64,2}) at ./number.jl:7
>  [2] cconvert(::Type, ::ForwardDiff.Dual{ForwardDiff.Tag{getfield(Main, Symbol("##77#78")),Float64},Float64,2}) at ./essentials.jl:344
>  [3] gammalogpdf(::ForwardDiff.Dual{ForwardDiff.Tag{getfield(Main, Symbol("##77#78")),Float64},Float64,2}, ::ForwardDiff.Dual{ForwardDiff.Tag{getfield(Main, Symbol("##77#78")),Float64},Float64,2}, ::Int64) at /Users/djohnson/.julia/packages/StatsFuns/0W2sM/src/rmath.jl:58
>  [4] (::getfield(Main, Symbol("##77#78")))(::Array{ForwardDiff.Dual{ForwardDiff.Tag{getfield(Main, Symbol("##77#78")),Float64},Float64,2},1}) at ./In[93]:3
>  [5] vector_mode_dual_eval(::getfield(Main, Symbol("##77#78")), ::Array{Float64,1}, ::ForwardDiff.GradientConfig{ForwardDiff.Tag{getfield(Main, Symbol("##77#78")),Float64},Float64,2,Array{ForwardDiff.Dual{ForwardDiff.Tag{getfield(Main, Symbol("##77#78")),Float64},Float64,2},1}}) at /Users/djohnson/.julia/packages/ForwardDiff/hnKaN/src/apiutils.jl:35
>  [6] vector_mode_gradient(::getfield(Main, Symbol("##77#78")), ::Array{Float64,1}, ::ForwardDiff.GradientConfig{ForwardDiff.Tag{getfield(Main, Symbol("##77#78")),Float64},Float64,2,Array{ForwardDiff.Dual{ForwardDiff.Tag{getfield(Main, Symbol("##77#78")),Float64},Float64,2},1}}) at /Users/djohnson/.julia/packages/ForwardDiff/hnKaN/src/gradient.jl:96
>  [7] gradient(::Function, ::Array{Float64,1}, ::ForwardDiff.GradientConfig{ForwardDiff.Tag{getfield(Main, Symbol("##77#78")),Float64},Float64,2,Array{ForwardDiff.Dual{ForwardDiff.Tag{getfield(Main, Symbol("##77#78")),Float64},Float64,2},1}}, ::Val{true}) at /Users/djohnson/.julia/packages/ForwardDiff/hnKaN/src/gradient.jl:17
>  [8] gradient(::Function, ::Array{Float64,1}, ::ForwardDiff.GradientConfig{ForwardDiff.Tag{getfield(Main, Symbol("##77#78")),Float64},Float64,2,Array{ForwardDiff.Dual{ForwardDiff.Tag{getfield(Main, Symbol("##77#78")),Float64},Float64,2},1}}) at /Users/djohnson/.julia/packages/ForwardDiff/hnKaN/src/gradient.jl:15 (repeats 2 times)
>  [9] top-level scope at In[93]:3

**Comment by ngiann** [comment] 2018-11-22 12:48
Same problem occurs with the Hessian too.

**Comment by devmotion** [comment] 2019-05-24 12:21
Do you still have these issues? All examples mentioned here (including Hessians) work for me on Julia 1.1.1 with StatsFuns v0.8.0 and ForwardDiff v0.10.3. Maybe the problems were fixed by https://github.com/JuliaStats/StatsFuns.jl/pull/65?

**Comment by devmotion** [comment] 2021-04-06 20:05
As mentioned above, I can't reproduce the errors anymore. Both examples work on recent versions of StatsFuns, therefore I'll close this issue.

**Closed by devmotion** 2021-04-06 20:05 UTC
