### ISSUE TITLE
v0.3.0 breaks Distributions.jl

### ISSUE THREAD

**Issue by tpoisot** [JuliaStats/StatsFuns.jl#11] opened 2016-07-15 19:13 UTC
I have a laptop running StatsFuns 0.2.2, and all code relying on Distributions works well. On other machines on which StatsFun is updated, I got:

~~~
ERROR: UndefVarError: Rmath not defined
 in _rand! at /home/myusername/.julia/v0.4/Distributions/src/genericrand.jl:7
~~~

Here is my versioninfo (for one of the problematic machines)
~~~
julia> versioninfo()
Julia Version 0.4.6
Commit 2e358ce* (2016-06-19 17:16 UTC)
Platform Info:
  System: Linux (x86_64-redhat-linux)
  CPU: Intel(R) Xeon(R) CPU E5-2683 v3 @ 2.00GHz
  WORD_SIZE: 64
  BLAS: libopenblas (DYNAMIC_ARCH NO_AFFINITY Haswell)
  LAPACK: libopenblasp.so.0
  LIBM: libopenlibm
  LLVM: libLLVM-3.3
~~~

**Comment by tpoisot** [comment] 2016-07-15 19:14
I ran `Pkg.update()` on my laptop, StatsFuns updated, and sure enough it broke everyhting related to generating random numbers through Distributions.

**Comment by ararslan** [comment] 2016-07-15 19:15
Sorry, this is a known issue. I'm working on a fix and hope to have it available ASAP.

**Comment by ararslan** [comment] 2016-07-15 20:04
Can you try running `Pkg.update()` and trying again?

**Comment by ararslan** [comment] 2016-07-25 02:54
This all seems to be working as expected now (at least I can no longer reproduce failures) so I'll close the issue. Let me know if you run into any more issues.

**Closed by ararslan** 2016-07-25 02:54 UTC
