### ISSUE TITLE
Precompilation error - Malformed expression

### ISSUE THREAD

**Issue by ChrisFuelOR** [JuliaStats/StatsFuns.jl#146] opened 2022-07-22 17:30 UTC
Hi, I'm trying to use the Distributions package, which seems to have StatsFuns as a dependency.
When I try to precompile it, I get the following error message:

[ Info: Precompiling StatsFuns [4c63d2b9-4356-54db-8cca-17b64c39e42c]
ERROR: LoadError: syntax: **malformed expression**
Stacktrace:
 [1] top-level scope at C:\Users\username\.julia\packages\StatsFuns\vxSkw\src\StatsFuns.jl:10
 [2] include(::Function, ::Module, ::String) at .\Base.jl:380
 [3] include(::Module, ::String) at .\Base.jl:368
 [4] top-level scope at none:2
 [5] eval at .\boot.jl:331 [inlined]
 [6] eval(::Expr) at .\client.jl:467
 [7] top-level scope at .\none:3
in expression starting at C:\Users\username\.julia\packages\StatsFuns\vxSkw\src\StatsFuns.jl:10
ERROR: Failed to precompile StatsFuns [4c63d2b9-4356-54db-8cca-17b64c39e42c] to C:\Users\username\.julia\compiled\v1.5\StatsFuns\530lR_MjOqY.ji.
Stacktrace:
 [1] error(::String) at .\error.jl:33
 [2] compilecache(::Base.PkgId, ::String) at .\loading.jl:1305
 [3] _require(::Base.PkgId) at .\loading.jl:1030
 [4] require(::Base.PkgId) at .\loading.jl:928
 [5] require(::Module, ::Symbol) at .\loading.jl:923

Any idea why this error occurs or how to prevent it?
I'm using the most recent version of StatsFuns (v1.0.1).

Thanks in advance.

**Comment by devmotion** [comment] 2022-07-22 22:10
I assume that you might run into https://github.com/simonster/Reexport.jl/issues/22. Can you check the version of Reexport that you use (e.g. by inspecting the output of `] st --manifest`) and possibly update it?

**Comment by ChrisFuelOR** [comment] 2022-07-23 14:35
Thanks for the suggestion. The command of `] st --manifest)` shows that I use Reexport v1.2.2, which should be the most current version.

**Comment by devmotion** [comment] 2023-02-01 12:50
I'll close this issue since I have not been able to reproduce the problem and tests on Github pass successfully without precompilation errors. Please reopen the issue if the problem persists.

**Closed by devmotion** 2023-02-01 12:50 UTC
