### ISSUE TITLE
logsumexp over matrix of infinities outputs NaN

### ISSUE THREAD

**Issue by MartinKocour** [JuliaStats/StatsFuns.jl#100] opened 2020-07-01 13:23 UTC
Hi I found a bug.

logsumexp over matrix of infinities outputs NaN in case of summing over dimension.

For instance:
```
 A = [-15   -10  -Inf;
     -Inf   -Inf  -Inf;
     -Inf   -Inf  -Inf]
logsumexp(A, dims=1)
```
outputs:
`1×3 Array{Float64,2}:
 -15.7909  -15.7909  NaN`

It should be:
`1×3 Array{Float64,2}:
 -15.7909  -15.7909  -Inf`

The problem is caused by subtraction:
`X .- u` where u is `[-15   -10  -Inf]` in this case

I would suggest to add the following lines to the code:
```
v = u .+ log.(sum(exp.(X .- u); dims=dims))
i = .! isfinite.(v)
v[i] .= u[i]
return v
```

**Comment by devmotion** [comment] 2020-12-26 13:08
I can't reproduce this issue with StatsFuns 0.9.6, I get
```julia
julia> logsumexp(A, dims=1)
1×3 Array{Float64,2}:
 -15.0  -10.0  -Inf
```
This seems to be the correct result (the suggestion `1×3 Array{Float64,2}: -15.7909 -15.7909 -Inf` seems to be incorrect). Maybe it was fixed by https://github.com/JuliaStats/StatsFuns.jl/pull/97?

**Closed** 2021-04-06 20:06 UTC
